- name: "Set proxmox_vm_from_template_delegate to proxmox host"
  set_fact:
    proxmox_vm_from_template_delegate: "{{ proxmox_vm_from_template_target_host }}"
  when: proxmox_vm_from_template_meta_host
- name: "Construct proxmox_vm_from_template_update_super_fact"
  set_fact:
    proxmox_vm_from_template_update_super_fact: |
      {% if item.key not in proxmox_vm_from_template_update_super_fact %}
      {{ proxmox_vm_from_template_update_super_fact | combine({item.key: item.value}) }}
      {% endif %}
  with_items: "{{ proxmox_vm_from_template_update | dict2items }}"
  when:
    - proxmox_vm_from_template_update is defined
