---
# tasks file for coreyramirezgomez.proxmox_vm_from_template
- name: Include assertions
  include_tasks: "assertions.yml"
- name: Include facts tasks
  include_tasks: "facts.yml"
- name: Include requirements tasks
  include_tasks: "requirements.yml"
- name: Include VM Tasks
  include_tasks: "vm.yml"
- name: Include Cloud-Init Tasks
  include_tasks: "cloud-init.yml"
  when:
    - proxmox_vm_from_template_ci_user_data_file_path is defined
    - proxmox_vm_from_template_ci_user_data_file_name is defined
    - proxmox_vm_from_template_ci_user_data_volume is defined
