---
- name: Install Python Requirements
  package:
    name: "{{ pkg_var }}"
    state: present
  with_items: "{{ proxmox_vm_from_template_required_packages }}"
  loop_control:
    loop_var: "pkg_var"
  delegate_to: "{{ proxmox_vm_from_template_delegate }}"
- name: Install Python Pacakge Requirements
  pip:
    executable: pip3
    name: "{{ pip_var }}"
  with_items: "{{ proxmox_vm_from_template_required_pip_packages }}"
  loop_control:
    loop_var: "pip_var"
  delegate_to: "{{ proxmox_vm_from_template_delegate }}"
